# Generated by Django 6.0.3 on 2026-03-25 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fileserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('physicalprefix', models.CharField(help_text='A prefix on the fileserver, like D:\\Shares', max_length=30)),
                ('logicalprefix', models.CharField(help_text='A logical prefix the user sees, like O:', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Permissionsfolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fileserver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.fileserver')),
                ('parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.folder')),
            ],
        ),
    ]
