# Generated by Django 6.0.3 on 2026-03-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_permissionsfolder_alter_folder_fileserver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMountPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logicalprefix', models.CharField(help_text='A logical prefix the user sees, like O:', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='fileserver',
            name='logicalprefix',
        ),
        migrations.RemoveField(
            model_name='fileserver',
            name='physicalprefix',
        ),
        migrations.CreateModel(
            name='OrgFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.orgfolder')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orgfolder')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMountPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physicalprefix', models.CharField(help_text='A prefix on the fileserver, like D:\\Shares', max_length=30)),
                ('fileserver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.fileserver')),
            ],
        ),
        migrations.AddField(
            model_name='orgfolder',
            name='physical_mountpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.physicalmountpoint'),
        ),
        migrations.AddField(
            model_name='orgfolder',
            name='virtual_mountpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.virtualmountpoint'),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
